version: '3'
volumes:
    postgres:
        driver: local

services:
    postgres:
        image: postgres:9.6
        environment:
            - POSTGRES_USER=api
            - POSTGRES_PASSWORD=api
            - POSTGRES_DB=api
        # persist the postgres data to disk so we don't lose it
        # on rebuilds.
        volumes:
            - ./postgres:/var/lib/postgresql/data
        ports:
            - '5432:5432'

    relayer:
        #image: registry.gitlab.com/startblockonline/likelib-relayer
        build:
            context: likelib-relayer/
            dockerfile: Dockerfile
        environment:
            - POSTGRES_URI=postgresql://api:api@postgres/api
        ports:
            - '3000:3000'

    ui:
        #image: registry.gitlab.com/startblockonline/likelib-exchange-ui
        build:
            context: likelib-exchange-ui/
            dockerfile: Dockerfile
        ports:
            - '80:80'

    pgadmin:
        container_name: pgadmin4_container
        image: dpage/pgadmin4
        restart: always
        environment:
            PGADMIN_DEFAULT_EMAIL: admin@email.com
            PGADMIN_DEFAULT_PASSWORD: hqhpVdKNNqYs3QTv
        ports:
            - "5050:80"
